In [1]:
#Data Analysis
import pandas as pd
import numpy as np
#Visualisation
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
data=pd.read_csv("C:\\Users\\Rahul\\Downloads\\telecommunications_churn (2).csv")

In [3]:
data.head()

,account_length,voice_mail_plan,voice_mail_messages,day_mins,evening_mins,night_mins,international_mins,customer_service_calls,international_plan,day_calls,day_charge,evening_calls,evening_charge,night_calls,night_charge,international_calls,international_charge,total_charge,churn
0,128,1,25,265.1,197.4,244.7,10.0,1,0,110,45.07,99,16.78,91,11.01,3,2.70,75.56,0
1,107,1,26,161.6,195.5,254.4,13.7,1,0,123,27.47,103,16.62,103,11.45,3,3.70,59.24,0
2,137,0,0,243.4,121.2,162.6,12.2,0,0,114,41.38,110,10.30,104,7.32,5,3.29,62.29,0
3,84,0,0,299.4,61.9,196.9,6.6,2,1,71,50.90,88,5.26,89,8.86,7,1.78,66.80,0
4,75,0,0,166.7,148.3,186.9,10.1,3,1,113,28.34,122,12.61,121,8.41,3,2.73,52.09,0

# To output some general information about the data

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3333 entries, 0 to 3332
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   account_length          3333 non-null   int64
 1   voice_mail_plan         3333 non-null   int64
 2   voice_mail_messages     3333 non-null   int64
 3   day_mins                3333 non-null   float64
 4   evening_mins            3333 non-null   float64
 5   night_mins              3333 non-null   float64
 6   international_mins      3333 non-null   float64
 7   customer_service_calls  3333 non-null   int64
 8   international_plan      3333 non-null   int64
 9   day_calls               3333 non-null   int64
 10  day_charge              3333 non-null   float64
 11  evening_calls           3333 non-null   int64
 12  evening_charge          3333 non-null   float64
 13  night_calls             3333 non-null   int64
 14  night_charge            3333 non-null   float64
 15  international_calls     3333 non-null   int64
 16  international_charge    3333 non-null   float64
 17  total_charge            3333 non-null   float64
 18  churn                   3333 non-null   int64
dtypes: float64(9), int64(10)
memory usage: 494.9 KB

In [5]:
data.shape

(3333, 19)

In [6]:
data.dtypes

account_length              int64
voice_mail_plan             int64
voice_mail_messages         int64
day_mins                  float64
evening_mins              float64
night_mins                float64
international_mins        float64
customer_service_calls      int64
international_plan          int64
day_calls                   int64
day_charge                float64
evening_calls               int64
evening_charge            float64
night_calls                 int64
night_charge              float64
international_calls         int64
international_charge      float64
total_charge              float64
churn                       int64
dtype: object

# To check on various statistical charachteristics of numerical features

In [7]:
data.describe()

,account_length,voice_mail_plan,voice_mail_messages,day_mins,evening_mins,night_mins,international_mins,customer_service_calls,international_plan,day_calls,day_charge,evening_calls,evening_charge,night_calls,night_charge,international_calls,international_charge,total_charge,churn
count,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000
mean,101.064806,0.276628,8.099010,179.775098,200.980348,200.872037,10.237294,1.562856,0.096910,100.435644,30.562307,100.114311,17.083540,100.107711,9.039325,4.479448,2.764581,59.449754,0.144914
std,39.822106,0.447398,13.688365,54.467389,50.713844,50.573847,2.791840,1.315491,0.295879,20.069084,9.259435,19.922625,4.310668,19.568609,2.275873,2.461214,0.753773,10.502261,0.352067
min,1.000000,0.000000,0.000000,0.000000,0.000000,23.200000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,33.000000,1.040000,0.000000,0.000000,22.930000,0.000000
25%,74.000000,0.000000,0.000000,143.700000,166.600000,167.000000,8.500000,1.000000,0.000000,87.000000,24.430000,87.000000,14.160000,87.000000,7.520000,3.000000,2.300000,52.380000,0.000000
50%,101.000000,0.000000,0.000000,179.400000,201.400000,201.200000,10.300000,1.000000,0.000000,101.000000,30.500000,100.000000,17.120000,100.000000,9.050000,4.000000,2.780000,59.470000,0.000000
75%,127.000000,1.000000,20.000000,216.400000,235.300000,235.300000,12.100000,2.000000,0.000000,114.000000,36.790000,114.000000,20.000000,113.000000,10.590000,6.000000,3.270000,66.480000,0.000000
max,243.000000,1.000000,51.000000,350.800000,363.700000,395.000000,20.000000,9.000000,1.000000,165.000000,59.640000,170.000000,30.910000,175.000000,17.770000,20.000000,5.400000,96.150000,1.000000

# value_counts method to have a look at the distribution and proportion

In [8]:
data['churn'].value_counts()

0    2850
1     483
Name: churn, dtype: int64

In [9]:
data['churn'].value_counts(normalize=True)

0    0.855086
1    0.144914
Name: churn, dtype: float64

# To display more than the std 5*20 matrix

In [10]:
pd.set_option('display.max_columns', 10)
pd.set_option('display.max_rows', 10)
print (data)

      account_length  voice_mail_plan  voice_mail_messages  day_mins  \
0                128                1                   25     265.1
1                107                1                   26     161.6
2                137                0                    0     243.4
3                 84                0                    0     299.4
4                 75                0                    0     166.7
...              ...              ...                  ...       ...
3328             192                1                   36     156.2
3329              68                0                    0     231.1
3330              28                0                    0     180.8
3331             184                0                    0     213.8
3332              74                1                   25     234.4

      evening_mins  ...  night_charge  international_calls  \
0            197.4  ...         11.01                    3
1            195.5  ...         11.45                    3
2            121.2  ...          7.32                    5
3             61.9  ...          8.86                    7
4            148.3  ...          8.41                    3
...            ...  ...           ...                  ...
3328         215.5  ...         12.56                    6
3329         153.4  ...          8.61                    4
3330         288.8  ...          8.64                    6
3331         159.6  ...          6.26                   10
3332         265.9  ...         10.86                    4

      international_charge  total_charge  churn
0                     2.70         75.56      0
1                     3.70         59.24      0
2                     3.29         62.29      0
3                     1.78         66.80      0
4                     2.73         52.09      0
...                    ...           ...    ...
3328                  2.67         60.10      0
3329                  2.59         63.53      0
3330                  3.81         67.74      0
3331                  1.35         57.53      0
3332                  3.70         77.01      0

[3333 rows x 19 columns]

# Distribution of categorical features

In [13]:
data.corr()

,account_length,voice_mail_plan,voice_mail_messages,day_mins,evening_mins,...,night_charge,international_calls,international_charge,total_charge,churn
account_length,1.000000,0.002918,-0.004628,0.006216,-0.006757,...,-0.008960,0.020661,0.009546,0.001454,0.016541
voice_mail_plan,0.002918,1.000000,0.956927,-0.001684,0.021545,...,0.006064,0.007618,-0.001276,0.008585,-0.102148
voice_mail_messages,-0.004628,0.956927,1.000000,0.000778,0.017562,...,0.007663,0.013957,0.002884,0.009766,-0.089728
day_mins,0.006216,-0.001684,0.000778,1.000000,0.007043,...,0.004300,0.008033,-0.010092,0.884754,0.205151
evening_mins,-0.006757,0.021545,0.017562,0.007043,1.000000,...,-0.012593,0.002541,-0.011067,0.413143,0.092796
...,...,...,...,...,...,...,...,...,...,...,...
night_charge,-0.008960,0.006064,0.007663,0.004300,-0.012593,...,1.000000,-0.012329,-0.015186,0.214233,0.035496
international_calls,0.020661,0.007618,0.013957,0.008033,0.002541,...,-0.012329,1.000000,0.032372,0.007776,-0.052844
international_charge,0.009546,-0.001276,0.002884,-0.010092,-0.011067,...,-0.015186,0.032372,1.000000,0.055036,0.068259
total_charge,0.001454,0.008585,0.009766,0.884754,0.413143,...,0.214233,0.007776,0.055036,1.000000,0.231549
churn,0.016541,-0.102148,-0.089728,0.205151,0.092796,...,0.035496,-0.052844,0.068259,0.231549,1.000000